version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    command: streamlit run frontend/app.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000